#include <wdm.h>

#define Trace(Level, Flags, Msg, ...) \
			DbgPrintEx(DPFLTR_IHVDRIVER_ID, DPFLTR_ERROR_LEVEL, "ST: %s (%i) " Msg "\n", Level, Flags, __VA_ARGS__);

//#define COORDS_DEBUG
//#define ALS_BACKLIGHT_DEBUG

typedef enum _TraceFlags
{
    TRACE_FLAG_INIT = 1,
    TRACE_FLAG_REGISTRY,
    TRACE_FLAG_HID,
    TRACE_FLAG_PNP,
    TRACE_FLAG_POWER,
    TRACE_FLAG_SPB,
    TRACE_FLAG_CONFIG,
    TRACE_FLAG_REPORTING,
    TRACE_FLAG_INTERRUPT,
    TRACE_FLAG_SAMPLES,
    TRACE_FLAG_OTHER,
    TRACE_FLAG_IDLE,
    TRACE_FLAG_DRIVER
} TraceFlag;

#define TRACE_LEVEL_ERROR "ERROR"
#define TRACE_LEVEL_VERBOSE "VERBOSE"
#define TRACE_LEVEL_INFORMATION "INFO"
#define TRACE_LEVEL_WARNING "WARN"
